### ISSUE TITLE
RxJS v5 suport

### ISSUE THREAD

**Issue by haoliangyu** [hellosmithy/chai-rx#2]
I wonder if there is any plan to support RxJS v5.

**Comment by haoliangyu** [comment]
I am closing this issue because there seems no nice official test suits in the current rxjs version yet.

**Comment by writtmeyer** [comment]
There actually is an extensive test suite (see spec folder) for rxjs v5.

**Comment by djalexd** [comment]
as far as I've seen, newer rx versions have been moved to a new package - instead of `rx` now it's called `rxjs` and makes the library to not even load :)

**Comment by hellosmithy** [comment]
@djalexd Currently this package only supports https://www.npmjs.com/package/rx up to versions 4.x.

I'm not planning to update it to RxJS v5 which is at `rxjs` as you say, as I don't use it so I'm not familiar with how the testing works on v5+. Although I'd happily accept a PR or even add a maintainer if anyone wishes to pursue that.

**Comment by djalexd** [comment]
@hellosmithy I created PR #5 but I'm not sure it's possible to support both rx and rxjs libraries at the same time (both lib and test file). For this reason, I have updated the `package.json`, and this would create a new NPM package (different name). Please feel free to review, discuss, merge. Thanks!
