### ISSUE TITLE
Support for Chai  > 4

### ISSUE THREAD

**Issue by Sciumo** [hellosmithy/chai-rx#3]
Chai 4 released in May.
Current:
  "peerDependencies": {
    "rx": ">= 4.0.7 < 5",
    "chai": ">= 2.1.2 < 4"
  },

**Comment by hellosmithy** [comment]
Resolved by https://github.com/hellosmithy/chai-rx/pull/4. Thanks @Sciumo

**Comment by rochdev** [comment]
@hellosmithy When will this be released?

**Comment by rochdev** [comment]
I am getting a `TypeError: fn is not a function` when using chai 4.0.2 with chai-rx 0.0.4 using this code:

```js
const chaiRx = require('chai-rx')
chai.use(chaiRx)
```

**Comment by rochdev** [comment]
Nevermind, it was compiled with babel so it needs an explicit default to be used with node:

```js
const chaiRx = require('chai-rx').default
chai.use(chaiRx)
```
